services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    networks:
      - default
  nginx:
    image: nginx:1.27
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - default
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - default

networks:
  default:
volumes:
  database_data:
